config/routes.rb
Rails.application.routes.draw do
  

  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :shops

  resources :users do
    resources :attendances, param: :worked_on, only:[:edit, :update] do  #->勤怠編集画面
      get :permit_logs, on: :collection                                          #->勤怠ログ
      post :permit_logs, on: :collection
    end
    member do
      get :info_edit
      patch :info_update
      get :overtime_confirm_modal
      get :edit_permit_modal
      get :month_modal
    end
    collection do
      post :import
      get :apis
      post :api_new
    end
   
  end

  resources :attendances, only:[:show] do
    resources :users, only:[] do
      get :overtime_modal_open, on: :collection
    
    end
   
    member do
      post :set_time
      patch :overtime_update    #=>残業申請アップデート
      patch :permit_request         #=>上長申請返信
      patch :edit_permit        #=>勤怠変更申請アップデート
    end
    get :working, on: :collection  #=>出勤社員
  end

  post '/data/:id',to: 'attendances#data', as: :data_post
  resources :months, only:[:update] do
    patch :response_superior, on: :member
  end

  root 'users#index'
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :number, presence: true
  validates :name, presence: true
  
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only:[:edit, :update, :destroy,]
  
  def index
    @shop = Shop.new
    @shops = Shop.all
  end

  def create
    @shop = Shop.new(shop_parameter)
  
    if @shop.save
      redirect_to shops_path, notice: '拠点を追加しました。'
    else
      render :index
    end
  end

  def edit
  end

  def update
    if @shop.update_attributes(shop_parameter)
      redirect_to shops_path, notice: '拠点を編集しました。'
    else  
      render :index
    end  
  end

  def destroy
    @shop.destroy
    redirect_to shops_path, notice: '拠点を削除しました。'
  end
  
  
private
  def shop_parameter
    params.require(:shop).permit(:number, :name, :category)
  end

  def set_shop
    @shop = Shop.find( params[:id] )
  end
  
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
 <div class="row">
    <div class="col-md-8 offset-2">
      <%= form_with model: shop, local:true do |f| %>
        <div class="form-group">
          <%= f.label :number %>
          <%= f.number_field :number, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group mb-5">
          <%= f.label :category %>
          <%= f.text_field :category, class: 'form-control' %>
        </div>
        <div class="text-center mt-3">
          <%= f.submit '送信', class: 'btn btn-primary btn-lg' %>
        </div>
     <% end %>
    </div>
  </div>

app/views/shops/_shop.html.erb
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-body">
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
         </button>
         <div class="text-center"><%= "[#{@shop.name}編集]" %></div>
         <div class="border-top mt-3 mb-3"></div>
         <%= render 'form', {shop: @shop} %>
      </div>   
    </div>
  </div>

app/views/shops/edit.js.erb
$("#shop_modal").html("<%= escape_javascript(render 'shop') %>")
$("#shop_modal").modal("show")

app/views/shops/index.html.erb
 
 <div id="shop_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
 <% if @shop.errors.any?  %>
  <% @shop.errors.full_messages.each do |error| %>
    <div class="alert alert-danger mt-2"><%= error %></div>
  <% end %>
 <% end %>
<div class="text-center mt-5 mb-5"><h1>拠点一覧</h1></div>
<table class="table table-bordered table-striped mb-5">
  <thead>
    <th class="w-25"></th>
    <th class="w-25"></th>
    <th class="text-center">拠点番号</th>
    <th class="text-center">拠点名</th>
    <th class="text-center">拠点種類</th>
  </thead>
  <tbody>
   <% @shops.each do |shop| %>
    <tr>
      <td class="align-middle">
         <%= link_to '修正', edit_shop_path(shop), remote: true, class: 'btn btn-primary w-50' %>
      </td>

       <td class="align-middle text-center">
         <%= link_to '削除', shop_path(shop), data:{confirm: '削除しますか？'}, method: :delete, class: 'btn btn-primary' %>
      </td>

      <td class="align-middle text-center"><%= shop.number %></td>
      <td class="align-middle text-center"><%= shop.name %></td>
      <td class="align-middle text-center"><%= shop.category %></td>
    </tr>
   <% end %>
  </tbody>
</table>
<div class="bg-light p-3">
 <button class="btn btn-primary btn-lg" id="shopBtn">拠点情報追加</button>
</div>
<div id="drop" class="shadow p-3 text-center">
  <%= render 'form',{shop: @shop} %>
</div>

<style>
  #drop{
    display: 'none';
  }
</style>