config/routes.rb
Rails.application.routes.draw do
  

  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :shops

  resources :users do
    resources :attendances, param: :worked_on, only:[:edit, :update] do  #->勤怠編集画面
      get :permit_logs, on: :collection                                          #->勤怠ログ
      post :permit_logs, on: :collection
    end
    member do
      get :info_edit
      patch :info_update
      get :overtime_confirm_modal
      get :edit_permit_modal
      get :month_modal
    end
    collection do
      post :import
      get :apis
      post :api_new
    end
   
  end

  resources :attendances, only:[:show] do
    resources :users, only:[] do
      get :overtime_modal_open, on: :collection
    
    end
   
    member do
      post :set_time
      patch :overtime_update    #=>残業申請アップデート
      patch :permit_request         #=>上長申請返信
      patch :edit_permit        #=>勤怠変更申請アップデート
    end
    get :working, on: :collection  #=>出勤社員
  end

  post '/data/:id',to: 'attendances#data', as: :data_post
  resources :months, only:[:update] do
    patch :response_superior, on: :member
  end

  root 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  require 'csv'
  has_secure_password
  has_many :attendances, dependent: :destroy
  has_many :months, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true,allow_blank: true
  validates :password_confirmation, presence: true,allow_blank: true

  def searchDay(first, last)
    self.attendances.where(worked_on: first .. last).order(id: :ASC)
  end


  #月合計稼働時間

  def month_total(monthData)
    total = 0.0
    monthData.each do |day|
      if day.started_at.present? && day.finished_at.present?
        total += day.day_total_time.to_i #->attendance model参照 
      end
    end
    return total
  end

  #契約稼働時間計算
  def operating_time_calc
    if self.start_work_time.present? && self.finish_work_time.present?
      start = self.start_work_time
      start_array = start.split(':')
      start_time = (start_array[0].to_i) * 60 + start_array[1].to_i
      
      finish = self.finish_work_time
      finish_array = finish.split(':')
      finish_time = (finish_array[0].to_i) * 60 + finish_array[1].to_i

      operating_time = (finish_time - start_time)/60.to_f
      return operating_time
    else
      return ''
    end
  end

  #csvインポート
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      attendance = find_by(id: row["id"]) || new
      attendance.attributes = row.to_hash.slice(*updatable_attributes)
      attendance.save!
    end
  end

  #csvキー配列
  def self.updatable_attributes
    [
      'name', 
      'email', 
      'password', 
      'password_confirmation', 
      'start_work_time', 
      'finish_work_time',
      'department',
      'employee_number',
      'uid',
      'superior'
    ]
  end
#上長ユーザー
scope :superior_select, -> { where(:superior => true)}
 
#上長確認残業申請済みattendance数

def superior_request_count
  counts = Attendance.where(superior_name: self.name).where(permit: :inprogress).count
  return counts ==0? 0 : counts
end

#上長確認編集申請attendance数
def edit_attendance_request_count
  Attendance.where(edit_superior_name: self.name).where(edit_permit: :inprogress2).count
end

#残業申請上長名で検索
def request_record(name)
  self.attendances.where(superior_name: name).where(permit: :inprogress)
end

#勤怠変更上長名で検索
def edit_request_record(name)
  self.attendances.where(edit_superior_name: name).where(edit_permit: :inprogress2)
end

#一ヶ月申請上長名で検索
def month_request_record(name)
  self.months.where(superior_name: name).where(permit_month: :inprogress3)
end

#月の申請数
  def month_request_count
    Month.where(superior_name: self.name).where(permit_month: :inprogress3).count
  end

#勤怠ログ用ベース
def permit_logs
  self.attendances.where(edit_permit: :ok2)
end

#勤怠ログ年 配列
  def log_years
    array = []
    array << '年'
    logs = self.permit_logs
    logs.each do |log|
      array << log.worked_on.strftime("%Y")
    end
    return array.uniq
  end

  #勤怠ログ年 配列
  def log_months
    array = []
    array << ' 月 '
    logs = self.permit_logs
    logs.each do |log|
      array << log.worked_on.strftime("%-m")
    end
    return array.uniq
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_set, only: [ :edit, :update, :destroy, :show, :month_modal]
  before_action :admin_check, only: [:index, :info_edit]
  before_action :other_user_access, only: [:show]
  skip_before_action :login_check, only: [ :apis ] 

  def index
    @users = User.all
  end

  def new
   @user = User.new
  end

  def create
    @user = User.new(user_parameter)
    if @user.save
      redirect_to @user, notice: "#{@user.name}を登録しました。"
    else  
      render :new
    end
    
  end

  def edit
  end

  def show
    if params[:first_day].nil?
      @first_day = Date.today.beginning_of_month
    else
      @first_day = Date.parse( params[:first_day]).beginning_of_month
    end
   
    @last_day = @first_day.end_of_month
    (@first_day .. @last_day).each do |day|
      unless @user.attendances.any?{|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    #月データ作成
    month = @user.months.where(request_month: @first_day.strftime('%m月')).where(year: @first_day.strftime('%Y')) 
    if month.count == 0 
      record = @user.months.build(
        request_month: @first_day.strftime('%m月'),
         year: @first_day.strftime('%Y'),
         base_day: @first_day
      )
      record.save
    end
    @days = @user.searchDay(@first_day, @last_day)
    @week = %w(日 月 火 水 木 金 土)
    @work_count = @user.attendances.work_count                           #-> modelより
    @overtime_request_count = @user.superior_request_count               #->残業申請数
    @month_count = @user.month_request_count                             #->1ヶ月申請数
    @edit_request_count = @user.edit_attendance_request_count
    @superior_name = superior_name  #=>ヘルパーメゾット
    @month = @user.months.find_by(request_month: @first_day.strftime('%m月') , year: @first_day.strftime('%Y'))
    respond_to do |format|
      format.html do
         
      end 
      format.csv do
        send_posts_csv(@days)
      end
    end
  end

  def update
    if @user.update_attributes(user_parameter)
      flash[:notice] = "#{@user.name}を編集しました。"
      current_user.admin? ? (redirect_to root_url) : (redirect_to @user)
    else  
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_url, notice: "削除しました。"
  else  
  end

#管理者による追加情報登録ページ
  def info_edit
    @user = User.find( params[:id] )
  end

#管理者による追加情報更新処理
  def info_update
    @user = User.find( params[:id] )
    if @userupdate_attribu.tes(user_parameter)
      redirect_to root_url, notice: "#{@user.name}の契約内容を更新しました。"
    else
      flash.now[:notice] = '失敗しました。'
      render :info_edit
    end
  end

#csvにてインポート
  def import
    @users = User.all
    CSV.foreach(params[:file].path, headers: true) do |row|
      user = User.find_by(id: row["id"]) || User.new
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save!
    end
    respond_to do |format|
      flash.now[:notice] = "インポートしました。"
      format.html { render :index }
    end
  end
  
  #残業申請ボタン押しした時モーダル
  def overtime_modal_open
    @attendance = Attendance.find( params[:attendance_id] )
    @week = %w(日 月 火 水 木 金 土)
    @superior_name = superior_name  #=>ヘルパーメゾット
    
  end
  
  #残業申請上長許可処理
  def overtime_confirm_modal
    @user = User.find( params[:id] )
    @week = %w(日 月 火 水 木 金 土)
    @request_attendances = Attendance.user_request(@user)
    @request_users = request_user_name       #=>helperより
  end
  
  #勤怠変更モーダル
  def edit_permit_modal
    @user = User.find( params[:id] )
    @week = %w(日 月 火 水 木 金 土)
    @request_attendances = Attendance.edit_request(@user)
    @request_users = request_user_name       #=>helperより
  end

  #一ヶ月申請モーダル
  def month_modal
    @request_months = Month.month_request(@user)
    @request_users = request_months_users
  end
  
 #api処理
 def apis
  @users = User.all
   render json: @users
 end

 #フロントエンドからユーザー送信登録
 def api_new
   puts params
 end

private
  def user_parameter
    params.require(:user).permit(
      :name, 
      :email, 
      :password, 
      :password_confirmation, 
      :department, 
      :start_work_time,
      :finish_work_time,
      :employee_number,
      :uid
    )
  end

  def user_set
    @user = User.find( params[:id] )
  end

  #管理者以外アクセス不可ユーザーページに戻る
  def admin_check
    redirect_to current_user,notice: '管理者専用です。' unless current_user.admin?
  end

   #管理者、上長以外URLで他のユーザーのページアクセス禁止
   def other_user_access
    user  = User.find( params[:id])
     if  user.id  != current_user.id
      unless (current_user.admin? || current_user.superior)
        redirect_to current_user,notice: '不正な操作です。'
      end
     end
   end

  
  
   def updatable_attributes
    [
      'name', 
      'email', 
      'password', 
      'password_confirmation', 
      'start_work_time', 
      'finish_work_time',
      'department',
      'employee_number',
      'uid',
      'superior'
    ]
  end
  
  
  
  
end

app/helpers/users_helper.rb
module UsersHelper
  def superior_name
    superior_users = User.superior_select
    array =[]
    array.push('')
    superior_users.each do |superior|
      unless current_user.name == superior.name
        array.push(superior.name)
      end 
     
    end
    return array
  end

  #勤怠変更申請中ユーザー名
  def request_user_name
    names = []
    @request_attendances.each do |attendance|
      names << attendance.user
    end
    return names.uniq
  end

  #一ヶ月申請中ユーザー名
  def request_months_users
    names = []
    @request_months.each do |month|
      names << month.user
    end
    return names.uniq
  end


end

app/views/users/_month.html.erb
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content" style="width:100%;">
      <div class="modal-body">
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= form_with model:@user, url: response_superior_month_path(@user,params:{day: params[:day]}), local: true, mehod: :patch  do |f| %>
         <% @request_users.each do | user| %>
            <div class="text-center mb-3"><h5><%= "[#{user.name}からの一ヶ月分申請]" %></h5></div>
            <table class="table table-bordered table-striped" style="font-size:12px">
               <thead>
                <tr>
                    <th class="text-center align-middle">月</th>
                    <th class="text-center align-middle">指示者確認㊞</th>
                    <th class="text-center align-middle">変更</th>
                    <th class="text-center align-middle">勤怠を確認する</th>
                </tr>
               </thead>
               <tbody>
               <% user.month_request_record(@user.name).each do |month| %>
                <%= f.fields_for "months[]", month do |af| %>
                <tr>
                  <td class="text-center align-middle"><%= month.request_month %></td>
                  <td class="text-center align-middle">
                    <%= af.select :permit_month, Month.permit_months.keys.map {|k| [I18n.t("enums.month.permit_month.#{k}"), k]}, {disabled: 0}, class: 'form-control' %>
                  </td>
                   <td class="text-center align-middle">
                    <%= af.check_box :check %>
                  </td>
                  <td class="text-center align-middle">
                   <%= link_to '勤怠確認', user_path(user,params:{first_day: month.base_day}), class: 'btn btn-primary btn-sm' %>
                  </td>
                </tr>
                <% end %>
               <% end %>
               </tbody>
              </table><br/>
         <% end %>
           <div class="text-center">
               <%= f.submit '変更を送信する', class: 'btn btn-primary'%>
           </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/_overtime_permit.html.erb
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
         <%= form_with model: @user, url: permit_request_attendance_path(@user,params:{day: params[:day]}), local: true,  method: :patch do |f| %>
       <% @request_users.each do |user| %>
        <% if user.request_record(@user.name).count >0 %>
          <div class="text-center mb-3"><h5><%= "[#{user.name}からの残業申請]" %></h5></div>
            <table class="table table-bordered" style="font-size:12px">
              <thead>
                <th class="text-center">日付</th>
                <th class="text-center">曜日</th>
                <th class="text-center">終了予定時間</th>
                <th class="text-center">指定勤務時間</th>
                <th class="text-center">時間外時間</th>
                <th class="text-center">業務処理内容</th>
                <th class="text-center">指示者確認㊞</th>
                <th class="text-center">変更</th>
                <th class="text-center">勤怠を確認する</th>
              </thead>
        
              <tbody class="bg-light text-center">
                <% user.request_record(@user.name).each do |attendance| %>
  　　　　　　　　　 <%= f.fields_for "attendances[]", attendance do |af| %>
                  <tr>
                      <td class="text-center"><%= l(attendance.worked_on, format: :short) %></td> 
                      <td class="text-center"><%= @week[attendance.worked_on.wday] %></td> 
                      <td class="text-center">
                        <%= l(attendance.overtime, format: :hour) + ":" + l(attendance.overtime, format: :min)  if attendance.overtime.present? %>
                      </td> 
                      <td class="text-center">
                        <%=  attendance.user.finish_work_time%>
                      </td> 
                      <td class="text-center">
                        <% if attendance.overtime.present? &&  attendance.user.finish_work_time.present? %>
                          <%=  overtime(attendance) %>
                        <% end %>
                      </td> 
                      <td><%= attendance.work_contents %></td>
                      <td><%= af.select :permit, Attendance.permits.keys.map {|k| [I18n.t("enums.attendance.permit.#{k}"), k]}, {disabled: 0}, class: 'form-control' %></td>
                      <td><%= af.check_box :change %></td>
                      
                      <td><%= link_to '勤怠確認', user_path(attendance.user,params:{first_day: attendance.worked_on}), class: 'btn btn-primary' %></td>
                  </tr>

                  <% end %>
                <% end %>
              </tbody>
            </table>
          <% end %>
         <% end %>
         <div class="text-center mt-5 pb-2"><%= f.submit "勤怠を変更する", class: "btn btn-primary btn-lg" %></div>
        <% end %>  
      </div>
    </div>
  </div>

app/views/users/_user.html.erb
<tr>
  <td style="border:none;" class="pb-n5">
    <%=link_to user.name, user_path(user), class:'font-weight-bold text-dark h6'%>
    <% unless user.admin %>
      <p></p>
      |<%= link_to "削除", user_path(user), method: :delete, id: "del#{user.id}", data:{confirm:"削除しますか？"}, class: "btn btn-primary" unless user.admin? %></td>
      <% end %>
  </td>
</tr>
<% unless user.admin %>
  <tr>
    <td style="border:none;" >
        <div  class="rounded pt-2 pb-1 shadow " style="border:none;background-color:#A4C6FF;margin-top:-2%;">
            <button 
            class='btn btn-primary btn-lg ml-2 accordion'
            id="<%= user.id %>"
            >編集</button> 
          <div id="hide<%=user.id %>" class="hide">
            <%= render 'user_edit',{user: user} %>
          </div>
        </div>
    </td>
  </tr>
 
<% end %>
<style>
  .hide{
    display:none;
  }
</style>
<script>
  
</script>
<!-- 
 <% unless user.admin %>
     
      <%= link_to "契約情報入力", info_edit_user_path(user), class: "btn btn-primary btn-lg mr-3" %>
       <%= link_to "編集", edit_user_path(user), class: "btn btn-primary btn-lg ml-2" %>
    <% end %>
-->

app/views/users/info_edit.html.erb
<div class="text-center mt-5 mb-5">
 <h1><%= "#{@user.name}契約情報入力" %></h1>
</div>

<div class="row">
    <div class="col-md-6 offset-3 bg-light shadow p-5">
        <%= form_with model: @user, url: info_update_user_path(@user) , local: true, method: :patch do |f| %>
            <div class="form-group">
                <%= f.label :department %>
                <%= f.text_field :department, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :start_work_time %>
                <%= f.time_field :start_work_time, class: 'form-control' %>
            </div>
             <div class="form-group">
                <%= f.label :finish_work_time %>
                <%= f.time_field :finish_work_time, class: 'form-control' %>
            </div>
            <div class="text-center mt-5">
                <%= f.submit '確定', class:'btn btn-primary btn-lg' %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="text-center mt-5 mb-5"><h1><%= "#{@user.name}詳細" %></h1></div>
<div id="over_time" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="over_time_permit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit_time_permit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="month_permit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>


<table class="table table-bordered">
  <tbody>
    <tr>
      <th class="bg-dark text-center text-white">
        <%= User.human_attribute_name :id %>
      </th>
      <td class="text-center">
        <%= @user.id %>
      </td>
      <th colspan="2" class="bg-dark text-center text-white">
        <%= User.human_attribute_name :name %>
      </th>
      <td colspan="2" class="text-center">
        <%= @user.name %>
      </td>
      <th class="bg-dark text-center text-white">
        <%= User.human_attribute_name :email %>
      </th>
      <td class="text-center">
        <%= @user.email %>
      </td>
    </tr>
    <!-- user info ２列目-->
    <tr>
      <th class="bg-dark text-center text-white">
        <%= User.human_attribute_name :department %>
      </th>
       <td class="text-center">
        <%= @user.department.present?? @user.department : '未登録' %>
      </td>
       <th class="bg-dark text-center text-white">
        <%= User.human_attribute_name :start_work_time %>
       </th>
       <td class="text-center">
        <%= @user.start_work_time.present?? @user.start_work_time : '未登録' %>
       </td>
       <th class="bg-dark text-center text-white">
         <%= User.human_attribute_name :finish_work_time %>
       </th>
       <td class="text-center">
         <%= @user.finish_work_time.present?? @user.finish_work_time : '未登録' %>
       </td>
       <th class="bg-dark text-center text-white">稼働時間</th>
       <td class="text-center">
         <%= "#{@user.operating_time_calc}時間" if @user.operating_time_calc.present? %>
       </td>
      
    </tr>
    <!-- user info 3列目-->
    <tr>
      <th class="bg-dark text-center text-white">
        <%= User.human_attribute_name :employee_number %>
      </th>
       <td colspan="3" class="text-center">
        <%= @user.employee_number.present?? @user.employee_number : '未登録' %>
      </td>
       <th class="bg-dark text-center text-white">
        <%= User.human_attribute_name :uid %>
       </th>
       <td colspan="3" class="text-center">
        <%= @user.uid.present?? @user.uid : '未登録' %>
       </td>
      
    </tr>
  </tbody>    
</table>
<div class="border-top"></div>
<div class="text-center mb-5 mt-2">勤怠管理表</div>
<% if @user == current_user || current_user.admin? %>
  <ul class="time-ul">
    <li class="time-list"><%= link_to "←", user_path(@user, params:{first_day: @first_day.prev_month}), class: 'btn btn-primary' %></li>
    <li class="time-list"><%= l(@first_day, format: :month) %></li>
    <li class="time-list"><%= link_to "→", user_path(@user, params:{first_day: @first_day.next_month}), class: 'btn btn-primary' %></li>
  </ul>
<% end %>

<div>
  <% if @user.superior %>
  　<div class="<%= @month_count == 0?'over_time_nil' : 'over_time_present'%>">
      [所属長承認申請のお知らせ]
      <%= link_to "#{@month_count}件の承認申請があります。",month_modal_user_path(@user,params:{day: @first_day}), remote: true, class:"user_request" if @month_count>0 %>
    </div>

    <div class="<%= @overtime_request_count == 0?'over_time_nil' : 'over_time_present'%>">
      [残業申請承認申請のお知らせ]
      <%= link_to "#{@overtime_request_count}件の残業申請があります。", overtime_confirm_modal_user_path(@user,params:{day: @first_day}), remote: true, class:"user_request" if @overtime_request_count>0 %>
    </div>

    <div class="<%= @edit_request_count == 0?'over_time_nil' : 'over_time_present'%>">
      [勤怠変更申請のお知らせ]
      <%= link_to "#{@edit_request_count}件の勤怠変更申請があります。", edit_permit_modal_user_path(@user,params:{day: @first_day}), remote: true, class:"user_request" if @edit_request_count>0 %>
    </div>
　<% end %>
</div>

<div class="row mt-2">
  <div class="col-md-3">
  <% if @user == current_user  %>
    <%=link_to '勤怠編集', edit_user_attendance_path(@user, @first_day), class: 'btn btn-primary mb-1' %>
    <%=link_to 'CSV出力', user_path(format: :csv), class: 'btn btn-primary mb-1' %>
    <%=link_to '勤怠ログ', permit_logs_user_attendances_path(@user), class: 'btn btn-primary btn-block' %>
  <% end %>
  </div>
</div>
 <span>(カッコ内の数字は申請中の未確定の数字)</span>
<table class="table table-bordered">
  <thead>
    <tr>
     <% if @user == current_user %>
      <th rowspan="3" class="bg-light text-center align-middle">残業申請</th>
     <% end %>
      <th rowspan="3" class="bg-light text-center align-middle">日付</th>
      <th rowspan="3" class="bg-light text-center align-middle">曜日</th>
      <th colspan="6" class="bg-light text-center align-middle">[実績]</th>
      <th colspan="7" class="bg-light text-center align-middle">所定外時間</th>
     
    </tr>
    <tr>
      <th colspan="3" class="bg-light text-center">出勤時間</th>
      <th colspan="3" class="bg-light text-center">退勤時間</th>
      <th rowspan="3" class="bg-light text-center align-middle">合計時間</th>
      <th rowspan="2" class="bg-light text-center align-middle">備考</th>
      <th colspan="2" class="bg-light text-center align-middle">終了予定時間</th>
      <th rowspan="2" class="bg-light text-center align-middle">時間外時間</th>
      <th rowspan="2" class="bg-light text-center align-middle">業務内容</th>
      <th rowspan="2" class="bg-light text-center align-middle">所属長承認㊞</th>
    </tr>
    <tr>
      <th class="bg-light text-center">時</th>
      <th class="bg-light text-center">分</th>
      <th class="bg-light text-center"></th>
    
      <th class="bg-light text-center">時</th>
      <th class="bg-light text-center">分</th>
      <th class="bg-light text-center"></th>

      <th class="bg-light text-center">時</th>
      <th class="bg-light text-center">分</th>
    </tr>
  </thead>
  <tbody class="align-middle">
    <% @days.each do |day| %>
      <tr>
        <% if @user == current_user %>
          <td class="text-center align-middle">
            <%= link_to '残業申請', overtime_modal_open_attendance_users_path(day), 
            id: "overtime#{day.id}", 
            remote: true, class: "#{day.finished_at.present?? '' : 'disabled'} btn btn-primary"%>
          </td>
        <% end %>
        <td class="text-center align-middle"><%= l(day.worked_on, format: :short) %></td>
        <td class="text-center align-middle"><%= @week[day.worked_on.wday] %></td>
        <td class="text-center align-middle">
          <%= l(day.started_at, format: :hour) if day.started_at.present?  %>
          <%= day.request_startedtime.present?? "<p class='text-danger'>(#{day.request_startedtime.strftime('%H')})</p>".html_safe : '' %>
        </td>

        <td class="text-center align-middle">
          <%= l(day.started_at, format: :min) if day.started_at.present?  %>
          <%= day.request_startedtime.present?? "<p class='text-danger'>(#{day.request_startedtime.strftime('%M')})</p>".html_safe : '' %>
        </td>
        <td class="text-center align-middle">
          <% if day.started_at.nil? && day.worked_on == Date.today && @user == current_user %>
            <%= button_to '出勤',set_time_attendance_path(day), class: 'btn btn-primary btn-block' %>
          <% end %>
        </td>

        <td class="text-center align-middle">
          <%= l(day.finished_at, format: :hour) if day.finished_at.present?  %>
          <%= day.request_finishedtime.present?? "<p class='text-danger'>(#{day.request_finishedtime.strftime('%H')})</p>".html_safe : '' %>
        </td>


        <td class="text-center align-middle">
          <%= l(day.finished_at, format: :min) if day.finished_at.present?  %>
           <%= day.request_finishedtime.present?? "<p class='text-danger'>(#{day.request_finishedtime.strftime('%M')})</p>".html_safe : '' %>
        </td>
        <td class="text-center align-middle">
          <% if day.finished_at.nil? && day.started_at.present? && day.worked_on == Date.today && @user == current_user %>
             <%= button_to '退勤',set_time_attendance_path(day), class: 'btn btn-primary btn-block' %>
          <% end %>
        </td>
        <td class="text-center align-middle">
         <% if day.started_at.present? && day.finished_at.present? %>
           <%= day.day_total_time %>
         <% end %>
        </td>
        <td class="text-center align-middle"><%= day.note %></td>
        <td class="text-center align-middle"><%= l(day.overtime, format: :hour) if day.overtime.present?  %></td>
        <td class="text-center align-middle"><%= l(day.overtime, format: :min) if day.overtime.present?  %></td>
        <td class="text-center align-middle"></td>
        <td class="text-center align-middle"><%= day.work_contents %></td>
        <td class="text-center align-middle" style="font-size:12px;">
           <%= day.enum_check.blank? ? "" : "<p class='permit-#{day.permit}'>#{day.enum_check}</p>".html_safe %>
           <%= day.edit_enum_check.blank? ? "" : "<p class='permit-#{day.edit_permit}'>#{day.edit_enum_check}</p>".html_safe %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th colspan="2" class="bg-light  align-middle">出勤日数</th>
    　<td colspan="4" class="text-center align-middle"><%= @work_count %>日</td>
    　<th colspan="2" class="bg-light align-middle">合計時間</th>
    　<td colspan="4" class="text-center align-middle">
       <%= @user.month_total(@days)%>
      </td>
      <td colspan="4" class="text-center">
      <% if @user == current_user %>
        <%= form_with model: @month, url: month_path(@month), local: true, method: :patch do |f|  %>
          <p>所属長承認&emsp;<%= @month.month_status %></p>
          <%= f.select :superior_name, @superior_name, {}, class: 'form-control mb-3' %>
          <%= f.submit '申請', class: 'btn btn-primary btn-block' %>
          <%= f.hidden_field :permit_month, value: :inprogress3 %>
          <%= f.hidden_field :base_day, value: @first_day %>
        <% end %>
      <% end %>  
      </td>
    </tr>
  </tfoot>
</table>
<style>
.time-ul{
  list-style: none;
  text-align:center
}
.time-list{
  display: inline;
  margin-right:20%;
}
.over_time_nil{
  color: black;
  font-weight: bold;
}
.over_time_present{
  color: red;
  font-weight: bold;
}
.user_request{
  color: red;
  border: 1px solid red;
  text-decoration: none;
}
.user_request:hover{
  text-decoration: none;
}
.permit-inprogress, .permit-inprogress2{
  color:black;
  font-weight:bold;
}
.permit-ok, .permit-ok2{
  color:blue;
  font-weight:bold;
}
.permit-not, .permit-not2{
  color:red;
  font-weight:bold;
}
</style>