config/routes.rb
Rails.application.routes.draw do
  

  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :shops

  resources :users do
    resources :attendances, param: :worked_on, only:[:edit, :update] do  #->勤怠編集画面
      get :permit_logs, on: :collection                                          #->勤怠ログ
      post :permit_logs, on: :collection
    end
    member do
      get :info_edit
      patch :info_update
      get :overtime_confirm_modal
      get :edit_permit_modal
      get :month_modal
    end
    collection do
      post :import
      get :apis
      post :api_new
    end
   
  end

  resources :attendances, only:[:show] do
    resources :users, only:[] do
      get :overtime_modal_open, on: :collection
    
    end
   
    member do
      post :set_time
      patch :overtime_update    #=>残業申請アップデート
      patch :permit_request         #=>上長申請返信
      patch :edit_permit        #=>勤怠変更申請アップデート
    end
    get :working, on: :collection  #=>出勤社員
  end

  post '/data/:id',to: 'attendances#data', as: :data_post
  resources :months, only:[:update] do
    patch :response_superior, on: :member
  end

  root 'users#index'
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  enum permit:{
    inprogress: 1,
    ok: 2,
    not: 3
  }
  enum edit_permit:{
    inprogress2: 1,
    ok2: 2,
    not2: 3
  }

  #出勤時間

  def start_time_set
    time = Time.new(
        Time.now.year,
        Time.now.month,
        Time.now.day,
        Time.now.hour,
        Time.now.min, 0
      )
    self.started_at =time
    log = self.start_log.to_s
    log += "," + time.strftime("%H:%M")
    self.start_log = log
    self.save

  end

  #退勤時間

  def finish_time_set
    time = Time.new(
      Time.now.year,
      Time.now.month,
      Time.now.day,
      Time.now.hour,
      Time.now.min, 0
    )
    self.finished_at = time
    log = self.finish_log.to_s
    log += "," + time.strftime("%H:%M")
    self.finish_log = log
    self.save
  end
  #日別合計時間計算

  def day_total_time
      start_time = (self.started_at.hour.to_i * 60) + self.started_at.min.to_i
      finish_time = (self.finished_at.hour.to_i * 60) + self.finished_at.min.to_i
      format("%.2f",(finish_time -start_time) / 60)
  end
  
  #出勤日数
  scope :work_count, -> { where.not(finished_at: nil).count}
 
  #残業申請されているattendance
  scope :user_request, ->(user) { where(superior_name: user.name)}

  #勤怠変更申請されている attendance
  scope :edit_request, ->(user) { where(edit_superior_name: user.name).where(edit_permit: :inprogress2)}
 
  
  
  #enumによる分岐
  def enum_check
    case self.permit
    when 0
      return ''
    when "inprogress"
      return "#{self.superior_name}に残業申請中" if self.superior_name.present?
    when 'ok'
      return "#{self.superior_name}から残業承認済み" if self.superior_name.present?
    when 'not'
      return "#{self.superior_name}から残業否認済み" if self.superior_name.present?
    else
    end  
  end

  #enum勤怠編集編集による分岐
  def edit_enum_check
    case self.edit_permit
    when 0
      return ''
    when "inprogress2"
      return "#{self.edit_superior_name}に変更申請中" if self.edit_superior_name.present?
    when 'ok2'
      return "#{self.edit_superior_name}から変更承認済み" if self.edit_superior_name.present?
    when 'not2'
      return "#{self.edit_superior_name}から変更否認済み" if self.edit_superior_name.present?
    else
    end  
  end

  #出勤社員検索
  scope :working_users, -> { where.not(started_at: nil).where(finished_at: nil).where(worked_on: Date.today)}
 
  
 
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :setting, only:[ :edit, :update]
  before_action :admin_check, only:[ :working ]
  skip_before_action :verify_authenticity_token, only:[:permit_logs]

  def show
  end

  def edit
  end

  #勤怠ログページ
  def permit_logs
    @user = User.find( params[:user_id] )
    @logs = @user.permit_logs
    @years = @user.log_years 
    @months =@user.log_months
  
  end

  def data
   data = params[:year].to_s + "-" + params[:month].to_s + "-01"
   @first_day = Date.parse(data)
   @last_day = @first_day.end_of_month
   @user = User.find( params[:id] )
   @datas = @user.attendances.where(worked_on: @first_day .. @last_day).where(edit_permit: :ok2)
   @datas = @datas.to_json.html_safe
   
  end
 


  def update
    if params_check                                                    #=>helper参照
      attendance_parameter.each do |id, value|
        attendance = Attendance.find id
        if value[:edit_superior_name] == "" && !value[:request_startedtime].blank?
          attendance_parameter.each do |id, item|
            attendance = Attendance.find id
            attendance.update(request_startedtime: item[:request_startedtime], request_finishedtime: item[:request_finishedtime], note: item[:note]) #=>renderで自動入力状態を保つため
          end
          flash.now[:notice] ="申告先を選択してください。"
          render :edit
          return
        end
        attendance.update_attributes(value)
        attendance.update_attributes(edit_permit: :inprogress2)
      end
        redirect_to user_url(@user, params:{first_day: @first_day}),notice: "編集しました。"
    else
      attendance_parameter.each do |id, item|
        attendance = Attendance.find id
        attendance.update(request_startedtime: item[:request_startedtime], request_finishedtime: item[:request_finishedtime], note: item[:note]) #=>renderで自動入力状態を保つため
      end
      flash.now[:notice] ="編集失敗。"
      render :edit
    end  
  end

  #上長残業申請返信処理
  def permit_request
    user = User.find( params[:id] )
    attendance_parameter.each do |id, item|
      if item[:change] == '1'
        attendance = Attendance.find id
        attendance.update_attributes(item)
      end
    end
    redirect_to user_url(@user, params:{first_day: params[:day]}),notice: '申請処理しました。'
  end
  
  

  def set_time
  　message = ''
    @attendance = Attendance.find( params[:id] )
    if @attendance.started_at.nil?
      @attendance.start_time_set
      message = 'おはようございます'
    elsif @attendance.finished_at.nil?
      @attendance.finish_time_set
      message = 'お疲れ様です。'
    end
    redirect_to user_path(@attendance.user),notice: message
  end

  #残業申請処理
  def overtime_update
    @attendance = Attendance.find( params[:id] )
    if overtime_validation == false
      redirect_to user_url(@attendance.user, params:{first_day: @attendance.worked_on}), notice: '終了時間が不正です。'
    else
      if params[:attendance][:superior_name] == ""
        redirect_to user_url(@attendance.user, params:{first_day: @attendance.worked_on}), notice: '申告先を選択してください。'
        return
      end
      if params[:attendance][:tommorow_check] == '1'
        @tomorrow_attendance = @attendance.user.attendances.find_by(worked_on: @attendance.worked_on.tomorrow)
        @tomorrow_attendance.update_attributes(overtime_parameter)
      else  
        @attendance.update_attributes(overtime_parameter)
      end
      redirect_to user_path(@attendance.user, params:{first_day: @attendance.worked_on}),notice: '残業申請しました。'
    end
  end

#勤怠変更処理
def edit_permit
  @user = User.find( params[:id] )
  attendance_parameter.each do |id, item|
    if item[:edit_check] == '1'
      attendance = Attendance.find id
      if item[:edit_permit] == 'ok2'
        s_log = attendance.start_log.to_s
        f_log = attendance.finish_log.to_s
        s_log += ',' + attendance.request_startedtime.strftime("%H:%M")
        f_log += ','+  attendance.request_finishedtime.strftime("%H:%M")
        attendance.update_attributes(
          edit_permit: item[:edit_permit],
          started_at: attendance.request_startedtime,
          finished_at: attendance.request_finishedtime,
          request_startedtime: '',
          request_finishedtime: '',
          start_log: s_log,
          finish_log: f_log
        )
      elsif item[:edit_permit] == 'no2'
        attendance.update_attributes(
          edit_permit: item[:edit_permit],
          request_startedtime: '',
          request_finishedtime: ''
        )
      end
     
    end
  end
  redirect_to user_url(@user, params:{first_day: params[:day]})
end

def working
  @attendances = Attendance.working_users
end



  

private
  def attendance_parameter
    params.require(:user).permit(attendances:
      [
        :started_at, 
        :finished_at, 
        :note,
        :superior_name,
        :change,
        :permit,
        :request_startedtime,
        :request_finishedtime,
        :edit_superior_name,
        :edit_check,
        :edit_permit
      ]
      )[:attendances]
  end

  def overtime_parameter
    params.require(:attendance).permit(
      :overtime,
      :tommorow_check,
      :work_contents,
      :superior_name,
      :change,
      :permit
    )
  end

  def setting
    @user = User.find( params[:user_id])
    @first_day = Date.parse( params[:worked_on])
    @last_day = @first_day.end_of_month
    @days = @user.searchDay(@first_day, @last_day)
    @week = %w(日 月 火 水 木 金 土)
    @superior_name = superior_name
  end

  
  
  
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def params_check
    flag = []
    attendance_parameter.each do |id, item|
      if item[:request_startedtime].nil? && item[:request_finishedtime].nil? && item[:edit_superior_name].blank?
        next
      elsif item[:request_startedtime].blank? && item[:request_finishedtime].blank? && item[:edit_superior_name].blank?
        next
      elsif item[:request_startedtime] > item[:request_finishedtime]
        flag << false
      elsif item[:request_startedtime].blank? || item[:request_finishedtime].blank?
        flag << false
      else
        flag << true
      end
    end
    return flag.include?(false) ? false : true
  end

  #残業バリデーション計算　
  def overtime_validation
    finish_time = (@attendance.finished_at.hour.to_i * 60) + @attendance.finished_at.min.to_i
    if params[:attendance]["overtime(1i)"].blank?
      return false
    end
    overtime  = (params[:attendance]["overtime(4i)"].to_i) *60 + params[:attendance]["overtime(5i)"].to_i
    comp = overtime - finish_time
    return comp >= 0 ? true : false
  end
  

  #残業時間計算
  def overtime(attendance)
    plan = (attendance.overtime.hour.to_i * 60) + attendance.overtime.min.to_i  
    finish_time = attendance.user.finish_work_time
    finish_array = finish_time.split(':')
    finish = (finish_array[0].to_i * 60) + finish_array[1].to_i  
    format("%.2f",(plan - finish) / 60)
  end

  #申請配列
   def request_array
     ["申請中", "承認", "否認"]
   end

  #csv 出力
  def send_posts_csv(attendances)
    bom = "\uFEFF"
    csv_data = CSV.generate(bom) do |csv|
      header = %w(日付 出勤時間 退勤時間)
      csv << header

      attendances.each do |attendance|
        start = attendance.started_at.strftime("%H:%M") if attendance.started_at.present?
        finish =  attendance.finished_at.strftime("%H:%M") if attendance.finished_at.present?
        values = [
          attendance.worked_on, 
          start,
          finish
        ]
        csv << values
      end

    end
    send_data(csv_data,dispositon: 'attachment', filename: "勤怠.csv")
  end

end

app/views/attendances/data.js.erb
var datas =<%= @datas %>;
var tbody = '';
$("#tbody").empty();
 document.getElementById('resetLog').style.display = 'block';

datas.forEach(function(e){
  var start = e.start_log.split(',');
  var finish = e.finish_log.split(',');
  var dateParse = new Date(e.updated_at);
  var date = dateParse.getFullYear() + '-' + (dateParse.getMonth()+1) + '/' +dateParse.getDate();

  tbody += '<tr>';
  tbody += '<td class="text-center">'+ e.worked_on + '</td>';
  tbody += '<td class="text-center">'+ start[1] + '</td>';
  tbody += '<td class="text-center">'+ finish[1] + '</td>';
  tbody += '<td class="text-center">'+ start.slice(-1)[0] + '</td>';
  tbody += '<td class="text-center">'+ finish.slice(-1)[0] + '</td>';
  tbody += '<td class="text-center">'+ e.edit_superior_name  + '</td>';
  tbody += '<td class="text-center">'+ date  + '</td>';
  tbody += '</tr>';
});

$('#tbody').html(tbody);

app/views/attendances/edit.html.erb
<div class="text-center mt-5 mb-5"><h1><%= "#{@user.name}さん勤怠編集" %></h1></div>
<% unless @errors.blank? %>
  <% @errors.each do |err| %>
    <div><%= err %></div>
  <% end %>
<% end %>

<%= form_with model: @user, url: user_attendance_path(@user, @first_day), method: :patch, local:true do |f| %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="bg-light text-center align-middle">日付</th>
      <th class="bg-light text-center align-middle">曜日</th>
      <th class="bg-light text-center">出勤時間</th>
      <th class="bg-light text-center">退勤時間</th>
      <th class="bg-light text-center align-middle">合計時間</th>
      <th class="bg-light text-center align-middle">備考</th>
      <th class="bg-light text-center align-middle">指示者確認㊞</th>
    </tr>
    
  </thead>
  <tbody>
    <% @days.each do |day| %>
    <%= f.fields_for "attendances[]", day do |af| %>
      <tr>
        <td class="text-center"><%= l(day.worked_on, format: :short)  %></td>
        <td class="text-center"><%= @week[day.worked_on.wday] %></td>
        <td><%= af.time_field :request_startedtime, class:'form-control' if day.worked_on < Date.today %></td>
        <td><%= af.time_field :request_finishedtime, class:'form-control' if day.worked_on < Date.today %></td>
        <td></td>
        <td><%= af.text_field :note, class:'form-control ' if day.worked_on < Date.today %></td>
        <td><%= af.select :edit_superior_name, @superior_name,{}, class:'form-control edit_select' %></td>
        
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<div class="text-center">
  <%= link_to '戻る', user_path(@user, params:{first_day: params[:worked_on]}), class:"btn btn-secondary btn-lg mr-3" %>
  <%= f.submit '編集', class: 'btn btn-primary btn-lg'%>
</div>
<% end %>

app/views/attendances/log.html.erb
<div class="text-center mt-5 mb-5"><h1>勤怠ログ</h1></div>
<button class="btn btn-secondary">リセット</button>

<div class="row">
 <div class="col-md-6">
 <!--最初のセレクト-->
   <div class="input-group">
    <label class="input-group-btn m-0" >
      <select class="custom-select" id="yearSelect">
        <option selected>年</option>
        <option value="one">One</option>
        <option value="Two">Two</option>
        <option value="Three">Three</option>
    　</select>
    </label>
    <input type="text" class="form-control" readonly="" id="yearText">
　 </div>
 <!--次のセレクト-->
   <div class="input-group" id="monthGroup">
    <label class="input-group-btn m-0" >
      <select class="custom-select" id="monthSelect">
        <option selected>月</option>
        <option value="one">One</option>
        <option value="Two">Two</option>
        <option value="Three">Three</option>
    　</select>
    </label>
    <input type="text" class="form-control" readonly="" id="monthText">
　 </div>
 </div>
</div>
<table class="table table-bordered table-striped" id="logTable">
      <thead>
        <tr>
            <th class="bg-light text-center">日付</th>
            <th class="bg-light text-center">変更前出社時間</th>
            <th class="bg-light text-center">変更前退社時間</th>
            <th class="bg-light text-center">変更後出社</th>
            <th class="bg-light text-center">変更後退社</th>
            <th class="bg-light text-center">指示者</th>
            <th class="bg-light text-center">承認日</th>
        </tr>
      </thead>
</table>

app/views/attendances/permit_logs.html.erb
<div class="text-center mt-5 mb-5"><h1>勤怠ログ</h1></div>

<button class="btn btn-secondary" id="resetLog">リセット</button>

<div class="row">
 <div class="col-md-6">
 <%= form_tag("/data/#{@user.id}", remote:true, id:'myform') do  %>
 <!--最初のセレクト-->
   <div class="input-group">
    <label class="input-group-btn m-0" style="width:15%;" >
      <%= select_tag :year_select,  options_for_select(@years), class:'custom-select', id: 'yearSelect' %>
    </label>
    <%= text_field_tag :year,nil, class: "form-control", readonly: true, id: "yearText" %>
　 </div>
 <!--次のセレクト-->
   <div class="input-group" id="monthGroup">
    <label class="input-group-btn m-0" style="width:15%;" >
        <%= select_tag :month_select, options_for_select(@months), class:'custom-select', id: 'monthSelect' %>
    </label>
    <%= text_field_tag :month, nil, class: "form-control", readonly: true,  id: "monthText" %>
　 </div>
 </div>
</div>

<% end %>
<table class="table table-bordered table-striped" id="logTable">
      <thead>
        <tr>
            <th class="bg-light text-center">日付</th>
            <th class="bg-light text-center">変更前出社時間</th>
            <th class="bg-light text-center">変更前退社時間</th>
            <th class="bg-light text-center">変更後出社</th>
            <th class="bg-light text-center">変更後退社</th>
            <th class="bg-light text-center">指示者</th>
            <th class="bg-light text-center">承認日</th>
        </tr>
      </thead>
      <tbody id="tbody">
       <td colspan="7" class="text-center">データがありません</td>
      </tbody>
</table>

app/views/attendances/working.html.erb
<div class="text-center mt-5 mb-5"><h1>出勤中社員一覧</h1></div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th class="text-center">社員番号</th>
            <th class="text-center">名前</th>
        </tr>
    </thead>
    <tbody>
     <% if @attendances.count == 0 %>
       <tr>
         <td class="text-center" colspan="2">出勤者なし</td>
       </tr>
     <% else %>
        <%  @attendances.each do |attendance| %>
        <tr>
            <td class="text-center"><%= attendance.user.employee_number.present? ? attendance.user.employee_number : '未登録' %></td>
            <td class="text-center"><%= attendance.user.name %></td>
        </tr>
      <% end %>
     <% end %>
     
    </tbody>
</table>