config/routes.rb
Rails.application.routes.draw do
  

  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :shops

  resources :users do
    resources :attendances, param: :worked_on, only:[:edit, :update] do  #->勤怠編集画面
      get :permit_logs, on: :collection                                          #->勤怠ログ
      post :permit_logs, on: :collection
    end
    member do
      get :info_edit
      patch :info_update
      get :overtime_confirm_modal
      get :edit_permit_modal
      get :month_modal
    end
    collection do
      post :import
      get :apis
      post :api_new
    end
   
  end

  resources :attendances, only:[:show] do
    resources :users, only:[] do
      get :overtime_modal_open, on: :collection
    
    end
   
    member do
      post :set_time
      patch :overtime_update    #=>残業申請アップデート
      patch :permit_request         #=>上長申請返信
      patch :edit_permit        #=>勤怠変更申請アップデート
    end
    get :working, on: :collection  #=>出勤社員
  end

  post '/data/:id',to: 'attendances#data', as: :data_post
  resources :months, only:[:update] do
    patch :response_superior, on: :member
  end

  root 'users#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <a class="navbar-brand text-white" href="#">勤怠アプリ</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

      
        <ul class="nav navbar-nav mr-auto">
         <% if current_user.present? && current_user.admin? %>
           <li class="nav_item">
            <%= link_to '従業員一覧',users_path, class: 'font-weight-bold text-white mr-3' %>
           </li>
           <li class="nav_item">
            <%= link_to '拠点情報',shops_path, class: 'font-weight-bold text-white mr-3' %>
           </li>
            <li class="nav_item">
            <%= link_to '出勤社員情報',working_attendances_path, class: 'font-weight-bold text-white mr-3' %>
           </li>
         <% end %>
        </ul>
    
         <ul class="nav navbar-nav mr-5">
          <% if current_user.present? %>
             <li class="nav-item dropdown mr-5">
              <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                メニュー
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %>
                <div class="dropdown-divider"></div>
                <%= link_to 'ユーザー編集', edit_user_path(current_user), class: 'dropdown-item' %>
                <%= link_to '勤怠ページ', current_user, class: 'dropdown-item' %>
              </div>
            </li>
          <% else %>  
             <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'font-weight-bold text-white' %></li>
          <% end %>
          </ul>
      

      </div>
    </nav>
    <div class="row">
      <div class="col-md-10 offset-1">
        <% if flash[:notice].present? %>
          <div class="alert alert-success"><%= flash[:notice] %></div>
        <% end %>
          <%= yield %>
      </div>
    </div>
  
  </body>
</html>